service: project-manager

frameworkVersion: '2'
useDotenv: true

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

plugins:
  - serverless-webpack

provider:
  name: 'aws'
  runtime: 'nodejs12.x'
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
  lambdaHashingVersion: '20201221'

functions:
  - ${file(./src/modules/projects/infra/serverless/lambdas.yml)}
